import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Hero from '../components/hero';
import ContentsList from '../components/ContentsList';
import { motion } from 'framer-motion';

export default function Home() {
  return (
    // <motion.div
    //   initial={{opacity:0}}
    //   animate={{ opacity: 1 }}
    //   exit={{ opacity: 0 }}    
    // >
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Hero />
        <div className={styles.CardWrapper}>
          <ContentsList 
            ImageSrc={"/033.jpeg"}
            ImageAlt={""}
            width={300}
            height={200}
            title={"Concept"}
            contents={"aaaaa"}
            ButtonLink={'/Concept-page'}
          />
          <ContentsList 
            ImageSrc={"/025.jpeg"}
            ImageAlt={""}
            width={300}
            height={200}
            title={"Price"}
            contents={"bbbb"}
            ButtonLink={'/Price-page'}
          />
          <ContentsList 
            ImageSrc={"/035.jpeg"}
            ImageAlt={""}
            width={300}
            height={200}
            title={"Salon"}
            contents={"ccccc"}
            ButtonLink={'/Salon-page'}
          />
        </div>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    // </motion.div>
  )
}
